import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'

export default defineConfig([
  // ios/ and android/ are generated by `cap add` and carry vendored JS
  // (native-bridge.js, cordova shims) that we neither wrote nor lint.
  globalIgnores([
    'dist',
    'dist-native',
    'ios',
    'android',
    // Playwright's own output, all regenerated.
    'playwright-report',
    'test-results',
    'blob-report',
  ]),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      globals: globals.browser,
    },
    rules: {
      /**
       * Two deliberate ways to name something you are not going to use, so
       * neither needs a `void x;` line after it to keep the linter quiet:
       *
       *   const { dirty: _d, ...rest } = row;   // omit a field by destructuring
       *   function Face({ size: _size }) {}     // accept a prop, ignore it
       *
       * `ignoreRestSiblings` is the idiom `stripLocal` and `partialize` are
       * built on; the `^_` patterns are what makes the underscore mean
       * anything.
       */
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          ignoreRestSiblings: true,
          args: 'after-used',
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
          destructuredArrayIgnorePattern: '^_',
        },
      ],
    },
  },
  {
    /* The three test layers plus their two configs. Node globals rather than
     * browser ones: these files run in node (vitest's `node` project, the
     * Playwright runner, the harness scripts), and the browser globals a spec
     * does touch live inside `page.evaluate` callbacks, which are typechecked
     * against DOM by tsconfig.test.json rather than linted as this file's
     * scope. `react-refresh` has no opinion worth hearing about a config's
     * default export. */
    files: ['tests/**/*.{ts,mjs}', 'vitest.config.ts', 'playwright.config.ts'],
    languageOptions: { globals: globals.node },
    rules: { 'react-refresh/only-export-components': 'off' },
  },
])
