#!/usr/bin/env node
/**
 * Regenerates `src/services/bible/verseCounts.ts` — how many verses each
 * chapter of the Bible holds, in English (KJV) versification.
 *
 * Why a table at all: drawing a verse uniformly out of the whole Bible needs
 * the weights up front. Without them the only options are "uniform per book,
 * then per chapter" (which makes an Obadiah verse hundreds of times likelier
 * than a Psalms one) or fetching chapters until one is accepted.
 *
 * Why KJV: `BookEntry.chapters` in bookCatalog.ts is already English
 * versification, and this script asserts the two agree. The German texts
 * legitimately differ — which is exactly why the drawn *verse* is picked from
 * the text that actually comes back, never from this table.
 *
 * Run `npm run bible:build` first if the packs aren't there yet.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const PACKS = join(ROOT, 'public', 'bible-packs');
const OUT = join(ROOT, 'src', 'services', 'bible', 'verseCounts.ts');
const SOURCE_TRANSLATION = 'KJV';

function fail(msg) {
  console.error(`buildVerseCounts: ${msg}`);
  process.exit(1);
}

const manifestPath = join(PACKS, 'manifest.json');
if (!existsSync(manifestPath)) fail(`no ${manifestPath} — run \`npm run bible:build\` first`);
const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));
const pack = manifest.translations?.find((t) => t.code === SOURCE_TRANSLATION);
if (!pack) fail(`manifest has no ${SOURCE_TRANSLATION} pack`);

// Book names + chapter counts straight out of the catalog, so the generated
// file is checked against the same source of truth the app parses references
// with rather than a second copy of the book list.
const catalog = [];
const catalogSrc = readFileSync(join(ROOT, 'src', 'services', 'bible', 'bookCatalog.ts'), 'utf8');
const bookRe = /\{ id: (\d+),[^}]*?nameEn: '([^']+)'[^}]*?chapters: (\d+) \}/g;
for (let m; (m = bookRe.exec(catalogSrc)); ) {
  catalog.push({ id: Number(m[1]), nameEn: m[2], chapters: Number(m[3]) });
}
if (catalog.length !== 66) fail(`parsed ${catalog.length} books from bookCatalog.ts, expected 66`);

const rows = [];
let totalVerses = 0;
let totalChapters = 0;

for (const book of catalog) {
  const entry = pack.books?.find((b) => b.b === book.id);
  if (!entry) fail(`${SOURCE_TRANSLATION} pack has no book ${book.id} (${book.nameEn})`);
  const data = JSON.parse(readFileSync(join(PACKS, entry.path), 'utf8'));
  const counts = [];
  for (let c = 1; c <= book.chapters; c++) {
    const verses = data.c?.[String(c)];
    if (!Array.isArray(verses) || verses.length === 0) {
      fail(`${book.nameEn} ${c} missing from the ${SOURCE_TRANSLATION} pack`);
    }
    counts.push(verses.length);
  }
  const packChapters = Object.keys(data.c ?? {}).length;
  if (packChapters !== book.chapters) {
    fail(`${book.nameEn}: catalog says ${book.chapters} chapters, pack has ${packChapters}`);
  }
  totalChapters += counts.length;
  totalVerses += counts.reduce((a, n) => a + n, 0);
  rows.push({ id: book.id, name: book.nameEn, counts });
}

// The canonical KJV totals. A mismatch means the pack (or the parser that
// built it) changed shape, and silently reweighting the draw is worse than
// failing the regeneration.
if (totalChapters !== 1189) fail(`counted ${totalChapters} chapters, expected 1189`);
if (totalVerses !== 31102) fail(`counted ${totalVerses} verses, expected 31102`);

const width = Math.max(...rows.map((r) => r.name.length));
const body = rows
  .map((r) => {
    const label = `/* ${String(r.id).padStart(2)} ${r.name.padEnd(width)} */`;
    return `  ${label} [${r.counts.join(', ')}],`;
  })
  .join('\n');

const out = `// GENERATED by \`npm run bible:counts\` (scripts/bible/buildVerseCounts.mjs)
// from the ${SOURCE_TRANSLATION} pack. Do not edit by hand.
//
// Verses per chapter in English (KJV) versification, indexed by book id − 1;
// within a row, by chapter − 1. ${totalChapters} chapters, ${totalVerses} verses.
//
// These are *weights*, not a promise about any particular translation: the
// German texts genuinely differ (see CLAUDE.md, "versification gaps"). Anything
// picking an actual verse draws it from the chapter that comes back, so a
// shorter chapter can never yield an out-of-range verse.

export const VERSE_COUNTS: readonly (readonly number[])[] = [
${body}
];

/** Every verse in the Bible, KJV versification — the denominator of a uniform
 * whole-Bible draw. */
export const TOTAL_VERSES = ${totalVerses};

/** Every chapter in the Bible — the denominator of a uniform chapter draw. */
export const TOTAL_CHAPTERS = ${totalChapters};
`;

writeFileSync(OUT, out);
console.log(
  `buildVerseCounts: wrote ${OUT} — ${rows.length} books, ${totalChapters} chapters, ${totalVerses} verses`,
);
