/**
 * Write public/api/announcements.php: the words the app says around scripture,
 * for the server to recognise.
 *
 * A voice shared for scripture (see api/sponsorship.php) may read verses — and
 * the announcements around them, or it could not read a chapter at all: "Psalm,
 * chapter 117", "Galater, Kapitel 5, Verse 22 bis 26", "Verse 2". The server
 * has to tell those apart from arbitrary prose without being able to run the
 * client, so this hands it the client's own sources, verbatim:
 *
 *   - the `announce.*` templates from src/i18n/en.json and de.json;
 *   - every book's name in both languages, from the book catalog;
 *   - the separators Intl.ListFormat puts between verse numbers in a list
 *     ("1, 3 and 7"), asked of this runtime's Intl, as the app's is.
 *
 * Data only — the matcher is isAnnouncement() in api/sponsorship.php — and
 * pinned by tests/unit/announcements.test.ts, which feeds every announcement
 * the real buildPlaybackPlan() makes through it. Run after changing any of the
 * three sources; the test fails until you do.
 *
 * Run: npm run voices:announcements
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { BOOKS } from '../../src/services/bible/bookCatalog.ts';

const repo = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const LANGS = ['en', 'de'];
/** The templates playbackPlan.ts speaks with. `postBy` rides along for a
 * piece's heading (the `pieces` scope); the other five are scripture's. */
const KEYS = ['chapter', 'chapterVerse', 'chapterRange', 'chapterList', 'verse', 'postBy'];

const templates = {};
for (const lang of LANGS) {
  const announce = JSON.parse(readFileSync(join(repo, 'src', 'i18n', `${lang}.json`), 'utf8')).announce;
  templates[lang] = Object.fromEntries(
    KEYS.map((k) => {
      if (typeof announce?.[k] !== 'string') throw new Error(`${lang}.json has no announce.${k}`);
      return [k, announce[k]];
    }),
  );
}

const bookNames = {
  en: BOOKS.map((b) => b.nameEn),
  de: BOOKS.map((b) => b.nameDe),
};

/** What Intl.ListFormat puts between items: for two, and inside and at the end
 * of three or more. Distinct, in that order. */
function listSeparators(locale) {
  const f = new Intl.ListFormat(locale, { style: 'long', type: 'conjunction' });
  const two = f.format(['1', '2']);
  const three = f.format(['1', '2', '3']);
  const pair = two.slice(1, -1);
  const middle = three.slice(1, three.indexOf('2'));
  const last = three.slice(three.indexOf('2') + 1, -1);
  return [...new Set([pair, middle, last])];
}
const separators = Object.fromEntries(LANGS.map((l) => [l, listSeparators(l)]));

const php = (s) => `'${String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
const phpList = (items, indent) =>
  `[\n${items.map((v) => `${indent}    ${php(v)},`).join('\n')}\n${indent}]`;
const phpMap = (entries, indent, value) =>
  `[\n${entries.map(([k, v]) => `${indent}    ${php(k)} => ${value(v, `${indent}    `)},`).join('\n')}\n${indent}]`;

const out = `<?php
declare(strict_types=1);

// An include, not an endpoint — see APP_ROOT in api.php. Fetched directly this
// file must say nothing: it never runs api.php's ini_set('display_errors', '0').
if (!defined('APP_ROOT')) { http_response_code(404); exit; }

/**
 * GENERATED by \`npm run voices:announcements\` (scripts/voices/
 * buildAnnouncements.mjs) — do not edit; change the sources and run it again.
 *
 * The words the app says around scripture, which a voice shared for scripture
 * may therefore say too (isAnnouncement() in api/sponsorship.php): the
 * announce.* templates of src/i18n/en.json and de.json, every book's name from
 * src/services/bible/bookCatalog.ts, and the separators Intl.ListFormat puts
 * between the verse numbers of a list. tests/unit/announcements.test.ts fails
 * while this is out of date.
 */

const ANNOUNCE_TEMPLATES = ${phpMap(LANGS.map((l) => [l, templates[l]]), '', (t, i) => phpMap(Object.entries(t), i, (v) => php(v)))};

const ANNOUNCE_BOOK_NAMES = ${phpMap(LANGS.map((l) => [l, bookNames[l]]), '', (names, i) => phpList(names, i))};

const ANNOUNCE_LIST_SEPARATORS = ${phpMap(LANGS.map((l) => [l, separators[l]]), '', (seps, i) => phpList(seps, i))};
`;

const target = join(repo, 'public', 'api', 'announcements.php');
writeFileSync(target, out);
console.log(
  `wrote ${target.slice(repo.length + 1)}: ${KEYS.length} templates and ${BOOKS.length} books per language; ` +
    `list separators ${LANGS.map((l) => `${l} ${JSON.stringify(separators[l])}`).join(', ')}`,
);
